[project]
name = 'stacks-pyth-network'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[contracts.hk-cursor]
path = 'contracts/requirements/hk-cursor.clar'
clarity_version = 2
epoch = 2.4

[contracts.hk-merkle-tree-keccak160]
path = 'contracts/requirements/hk-merkle-tree-keccak160.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-governance]
path = 'contracts/pyth-governance.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-oracle]
path = 'contracts/pyth-oracle.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-store]
path = 'contracts/pyth-store.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-pnau-decoder]
path = 'contracts/pyth-pnau-decoder.clar'
clarity_version = 2
epoch = 2.4

[contracts.pyth-traits]
path = 'contracts/pyth-traits.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-core]
path = 'contracts/wormhole/wormhole-core.clar'
clarity_version = 2
epoch = 2.4

[contracts.wormhole-traits]
path = 'contracts/wormhole/wormhole-traits.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
